getsavvyinc/savvy-cli

- .goreleaser.yaml
- Makefile
- cmd/version.go
- cmd/whoami.go
- cmd/whoami: improve help message
- cmd/version: add version sub-command to the cli
> savvy: add version sub-command 

- cmd/init.go
- cmd/setup/savvy.zsh
- cmd/setup/zsh.go
- install/install.sh
- init/zsh: setup functions used to record commands in zsh shells
- install: include shell setup instructions in the install script
> "Ensure savvy can record commands across nested sub-shells" 

- client/client.go
- cmd/record.go
- savvy_errors/invalid.go
- savvy_errors/style.go
- client: Check client validity while it is being created.
- cmd/record: return early if the user is not logged in with a valid token
> Users must be logged in to run savvy record

- client/client.go
- cmd/record.go
- savvy_errors/invalid.go
- client: check for an invalid client
- cmd/record: if client is invalid; make sure the user knows they have to login
> Prompt users to login when the config file is missing

- .goreleaser.yaml
- Makefile
- client/client.go
- cmd/version.go
- config/config.go
- config/version.go
- refactor: set version as part of the config pkg
- config: set json encoding label for config object
- client: add X-Savvy-Version req Header
> add X-savvy-version req header

- flake.lock
- flake.nix
- shell.nix
> nix: move from shell.nix to flakes

- install/install.sh
- install: Group setup instructions together
- install: instructions on picking up the changes
- install: update discord CTA
> install: group setup instructions together

- cmd/login.go
- cmd/record.go
- config/dashboard_host.go
- config/host_dev.go
- config: add dashboard host
- login: call out to the dashboard for loggin in
- cmd/record: simplify defer when closing ptmx
> cmd/login: loggin in to the cli logs you in to the dashboard

- go.mod
- install/install.sh
- go.mod update go.mod
- use SHELL env var to detect default shell
> install: use SHELL to detect shell

- .envrc
- cmd/record.go
- cmd/setup/bash-preexec.sh
- cmd/setup/savvy.zsh
- flake.lock
- flake.nix
- shell/bash.go
- shell/check_bash_setup.go
- shell/check_setup.go
- shell/check_zsh_setup.go
- shell/zsh.go
- cmd/setup/bash-preexec.sh: we already expand aliases.
- cmd/record: update shell it starts up to verify setup
- rm gocode
- envrc
> record: check savvy setup and print instructions if required

- cmd/file.go
- display/error.go
- server/client.go
- server/unix_socket.go
- **display: ErrorMsg displays a string with the style of an error**
- **cmd/file: allow users to record files within a recording session**
> cmd/record: Allow users to record file content

- cmd/send.go
- cmd/setup/bash-preexec.sh
- **cmg/setup/bash: add support for ignoreErrors to bash**
- **cmd/send: print step_id only if we generated it**
> savvy record: add support for ignoreErrors in bash shells

- client/client.go
- cmd/component/generate_runbook.go
- cmd/history.go
- cmd/record.go
- cmd/send.go
- cmd/setup/savvy.zsh
- server/unix_socket.go
- **cmd/send: record prompt while the command is executed**
- **client,server: propogate recorded prompt along with the command to the api**
> record cmdline prompt to share more metadata

- client/client.go
- client/guest.go
- cmd/run.go
- **cmd/run: specify examples for savvy run**
- **cmd/run: run accepts 0 or 1 arguments**
- **client: Runbooks fetches all runbooks for a user**
- **cmd/run: users can select and run any runbook**
> cmd/run: users can select and run runbooks

- client/client.go
- client/guest.go
- cmd/ask.go
- cmd/setup/savvy.zsh
- **cmd/ask: setup skeleton**
- **zsh: setup auto complete**
- **cmd/ask: update example**
- **client: Ask Savvy to answer our question with list of commands**
- **cmd/ask: integrate client and impl ask**
> savvy ask: generate commands for users questions 

- client/client.go
- client/guest.go
- cmd/ask.go
- cmd/component/generate_runbook.go
- **cmd/ask: display runbooks instead of commands**
- **client: rm Answer type**
- **cmd/ask: display the runbook using charm**
> cmd/ask: rm answer type; display answers as runbooks

- cmd/ask.go
- cmd/component/list.go
- cmd/component/list/ask_delegate.go
- cmd/component/list/list.go
- cmd/record.go
- **component/list: refactor NewListModel to accept delegates**
- **mv component/list.go -> list/list.go**
- **component/list: add custom ask delegate**
- **cmd/ask: allow users to select a command and copy it to the clipboard**
> cmd/ask: select commands and store them in the clipboard

- install/install.sh
- **install: install savvy to /Users/shantanu/savvy/bin/**
- **install: improve font legibility and copy-pastability**
> install: update install location 

- cmd/ask.go
- cmd/explain.go
- **cmd/ask: start interactive mode if no args are provided**
- **cmd/explain: start interactive mode if no args provided**
> ask,explain: add interactive mode

- client/client.go
- client/guest.go
- cmd/ask.go
- cmd/component/list/list.go
- cmd/record.go
- slice/slice.go
- **client/Ask: Pass in prev conversation history**
- **slice: add Map func**
- **list: generalize adding help messages to the list**
- **slice: Check membership in slice**
- **cmd/ask: loop until user is happy with their answer**
- **cmd/ask: add past questions too**
> cmd/ask: refine prompts

- cmd/setup/savvy.zsh
- **Use print -rP when printing the prompt**
- **savvy.zsh: only print prompt when recording commands**
> Handle powerlevel10k prompt structure correctly

- cmd/setup/bash-preexec.sh
- cmd/setup/savvy.zsh
- **setup/zsh: Tell users how to exit savvy run when finished**
- **setup/bash-preexec.sh: tell users  how to exit savvy run shell on completion**
> Inform users how to exit savvy run shell on completion

- client/client.go
- client/guest.go
- cmd/ask.go
- cmd/browser/open.go
- cmd/component/list/list.go
- cmd/login.go
- **cmd/login: add runLoginCmd to check --force flags**
- **cmd/ask: User can save commands as a runbook**
- **browser: Open -> OpenCmd**
- **browser: Open invokes OpenCmd and starts the command.**
- **cmd/ask: save runbooks**
- **browser: display info about browser opening the url**
- **cmd/ask: Save and run commands**
> cmd/ask: Allow users to save and run commands from savvy ask"

- cmd/history.go
> savvy record history: cleanup server when user presses ctrl-C

- cmd/history.go
> chore: update history.go

- cmd/history.go
- go.mod
- go.sum
- **update cobra to 1.8.1**
- **history: unhide savvy record history**
> Update Cobra and fix savvy record history 

- client/client.go
- client/guest.go
- client/local/local.go
- cmd/run.go
- cmd/sync.go
- storage/storage.go
- **cmd/run: use smaller client.RunbookClient instead of the full client.**
- **storage: Write/Read runbooks to a local file**
- **client: Add a local client.**
- **add local flag to savvy run**
- **client: Runbooks add an opt to fetch all runbooks or just runbooks owned by a user**
- **storage: serialize using gob instead of json**
> Local Sync 

- go.mod
- go.sum
> upgrade-cli: v0.5.1 -> v0.6.0
