cmd/record.go
savvy_errors/style.go
server/unix_socket.go

- errors: Add function that appends a CTA to reach out to support to any error
- cmd/record: fail gracefully when user tries to create a concurrent recording session

Gracefully fail when a user tries to create multiple recording sessions

---

cmd/record.go
shell/zsh.go

- shell: use filepath.Join instead of os.FilePathSepartor
- shell/zsh: handle err from instantiating zshrc template
- cmd/record: handle err spawing sub-shell to record a guide
- cmd/record: handle error when putting ptty in raw mode
- cmd/record: do not panic if pty can't be restored
- cmd/record: handle errs displaying or generating a runbook after recording it

rm panics 

---

cmd/record.go
server/unix_socket.go
shell/zsh.go

- server: exit ListenAndServe after Listener has closed
- cmd/record: rm stray comment
- shell: create Command with exec.Command instead of exec.CommandContext

server: kill ListenAndServe when the server is closed

---

cmd/login.go
display/info.go

Fixes #1
- login: fix error formatting
- login: inline token check in runLogin
- display/info: rm color for info text
- login: return early if token is valid
- login: add --force/-f flag to force new login flow

login: return early if the token is valid

---

cmd/record.go
shell/zsh.go

- cmd/record: share runbook url with users at the end
- shell/zsh: rm unused hooks
- shell/zsh: support linux and macOS.
- shell/zsh: inform users how to stop recording

cmd/record: ux improvements

---

client/client.go
cmd/whoami.go

- client: handle nil response from defaultRoundTrip
- cmd/whoami: explicitly print error

cmd/whoami: handle nil response from default roundtripper 

---

cmd/record.go
shell/zsh.go

When the user presses exit or ctrl-d, the pty will be closed and
io.Copy(os.Stdout, ptmx) will unblock and we will call cancelCtx
This should get rid of the scenario where users press ctrl-d or exit and
the terminal just hangs blocked waiting for c.Wait() to unblock.
We force c.Wait() to unblock by cancelling the context.

cmd/record: cancel ctx for spawned sub-shell when pty closes

---

.github/workflows/go.yml
shell/detect.go
shell/detect_test.go
shell/zsh.go

- shell: detect and spawn a shell used to launch savvy record.
- shell: improve shell not supported error message

shell: robust shell detection 

---

cmd/init.go
cmd/setup/bash-preexec.sh
cmd/setup/bash.go
cmd/setup/zsh.go
shell/bash.go
shell/detect.go
shell/spawn.go
shell/zsh.go

- shell: add ability to create a bash sub-shell
- cmd: support bash and dash
- refactor(shell): extract spawn func into its own file
- cmd,shell: move logic to return SupportedShells into pkg shell
- setup/bash: add preexec and precmd funcs even when bash-preexec already exists
- set savvy_input_file

add support for bash 

---

cmd/send.go
cmd/setup/bash-preexec.sh
cmd/setup/savvy.zsh

Using echo to write data to a unix socket as if it is a regular file
"works", but it doesn't respect the usual protocol that `netcat` uses.
However, `netcat` comes in two main flavors. GNU and BSD.
BSD netcat has the -w and -U flag, both of which are missing form GNU.
The reliability of savvy record now has a hard dependency on the version
of netcat installed on the user's machine.
`socat` is a third alternative but that is not guaranteed to be
installed by default in most cases.
This commit introduces `savvy send` to address all the issue above.
`send` is a simple go program that creates a conn to the unix socket and
uses the go standard library to write data to the socket and close the
conn.
send will support all the platforms that Go supports by default and we
no longer rely on the …

send: use send instead of nc or echo to communicate with the unix socket

---

cmd/record.go
display/info.go

- **cmd/record: avoid context leak**
- **cmd/record: handle unused variables**
- **display: add Infof**

cmd/record: rm unused vars

---

cmd/history.go
cmd/logger.go
cmd/root.go
display/error.go
server/unix_socket.go

- **cmd/root: setup and inject a slog instance accessible to all sub commands**
- **history: add debug logs**
- **cmd/logger: isolate logger code into its own file**
- **cmd/root: set a default logger**
- **server: log accept conn error as debug log**
- **history: wait for pty to process all commands before we cancel the context**

debug: inject debug logger to all commands 

---

cmd/history.go
shell/bash.go

- **cmd/history: fix typo for psuedo terminal**
- **shell/bash: do not rely on SAVVY_LOGIN_SHELL for bash**
- **shell/bash: tail bash history**
- **shell/bash: spawn bash shell to expand the history commands**

record/history: add support for bash shells

---

cmd/history.go

i:e the oldest commands ( smallest unix timestamp ) will show up first.
This is the reverse order from where how the history is presented.
Usually, devs want to create a runbook from most recent commands, so we
show history in that order.
But once selected, we want to respect the chronology of time.

history: selected commands are sorted chronologically by time.

---

cmd/record.go
cmd/send.go
cmd/setup/savvy.zsh
idgen/gen.go
server/client.go
server/unix_socket.go

- **setup/savvy.zsh: track return code**
- **server: record command exit status and add support for ignoring errors**
- **cmd/record: add ignoreErrors flag**
- **idgen: generate id for each cmd**
- **cmd/send: generate recordedData for each step**
- **server: initialize map and rename vars**
- **server/client: todo: fix recording files**
- **server/client: update file recording to use new msg format**
- **setup/savvy.zsh: rm debug log**

savvy record: add ignoreErrors flag

---

cmd/send.go
cmd/setup/bash-preexec.sh
shell/expansion/ignore.go
shell/expansion/ignore_test.go

- **shell/expansion: ignore expansions of commands like grep**
- **bash-preexec.sh: expand bash aliases in pipes and process substitution**

shell/expansion: ignore annoying grep expansions

---

client/client.go
client/guest.go
cmd/run.go
cmd/setup/savvy.zsh
shell/bash.go
shell/spawn.go
shell/zsh.go

- **cmd: Add skeleton for savvy run**
- **client: Allow Guest clients**
- **cmd/run: enforce 1 positional argument**
- **client: deprecate GenerateRunbook in favor of GenerateRunbookV2**
- **client: Add separate Guest client for fetching public runbooks**
- **cmd/run: fetch runbook from guest|loggedin client**
- **cmd/run: fetch runbook by runbook id**
- **cmd/run: Display spinner while we fetch the runbook**
- **client: Track runbook ID returned by Savvy's API**
- **shell: Extend shell interface to support running a runbook**
- **shell/zsh: extract common setup code into baseScript**
- **client: Fetch Commands from a client runbook**
- **shell: impl SpawnRunbookRunner**
- **cmd/run: run runbooks in a savvy sub shell**
- **cmd/run: savvy run works for zsh**
- **savvy run: Add runbook name …

savvy run: run runbooks from your terminal 

---

cmd/setup/savvy.zsh
shell/zsh.go

When using the literal `,` as a delimeter, we can't split on `,` to
reconstruct the sequence of commands as an array in zsh.
Commands like grep --exlcude-dir{.git,foo,etc} include false positives.
One alternative is to escape those commands, but using COMMA is simpler.
We also take this opportunity to use `@s` instead of just `s` while
splitting the string.
@s preserves the spacing and quotes around string

shell/zsh: use COMMA as a delimter when passing in SAVVY_RUNBOOK_COMMANDS

---

cmd/setup/bash-preexec.sh
shell/bash.go
shell/kind/kind.go
shell/spawn.go
shell/zsh.go

- **setup/bash: trigger command completion**
- **setup/bash: Add precmd,preexec and completion binding to automatically run runbooks**
- **setup/bash: Add support for SAVVY_CONTEXT = run|record**
- **shell/zsh: Setup env vars for runner shell in one func.**
- **shell/bash: Impl SpawnRunbookRunner**
- **shell: trim leading and trailing hyphen from runbook alias**
- **shell/kind: add unknown shell kind**
- **shell: SAVVY_NEXT_STEP defaults to zero for bash and one for zsh**

savvy run: support bash 

---

ingest/main.go

- **ingestion: use command as part of embedding for explanation.**
- **inc concurrency for writing to the db**

ingestion: add command to explanation while creating embeddings

---

cmd/history.go
cmd/record.go
server/client.go
server/unix_socket.go

- **cmd/record: detect and fix concurrent recording sessions**
- **server: detect permanent net.OpErr and exit listen loop**
- **cmd/record: simplify code**
- **server: removing the socket doesn't end the listener; so we send a shutdown signal**
- **server: resolve concurrent errors within the server pkg**
- **cmd/history: check for multiple recordings before user selects commands**
- **history: shutdown signal should kill the shell**

detect and handle multiple recording errors

---

cmd/history.go
cmd/internal/current.go
cmd/internal/internal.go
cmd/internal/next.go
cmd/internal/set-param.go
cmd/root.go
cmd/run.go
cmd/setup/bash-preexec.sh
cmd/setup/savvy.zsh
cmd/write.go
server/cleanup/permission.go
server/client.go
server/mode/mode.go
server/run/client.go
server/run/run.go
server/run/run_test.go
server/unix_socket.go

- **cmd/internal: setup internal cmds**
- **parse params**
- **server/client: Create client for any socket path**
- **server: DRY cleanup socket committed**
- **client: Add a shutdown interface**
- **server/run: Add a run server**
- **savvy.zsh: only use zle to trigger runner**
- **server/client: SendShutdown returns an err**
- **server/run: Update state based on commands**
- **server/run: Add client for run server**
- **cmd/run: use runServer to coordinate state**
- **server/run: disambiguate client struct from pkg**
- **cmd/internal: impl current and next**
- **change return data for next and current**
- **cmd/history: handle err starting record server**
- **run: start server**
- **server/run: read json messages instead of waiting for client to close the conn**
- **close client conn …

Introduce internal commands to manage execution state

---

cmd/internal/current.go
cmd/internal/next.go
cmd/internal/set-param.go
cmd/internal/set-param_test.go
cmd/setup/bash-preexec.sh
cmd/setup/savvy.zsh
param/param.go
param/param_test.go
server/run/client.go
server/run/run.go
server/run/run_test.go
shell/zsh.go
slice/slice.go

- **server/run: Update default run socket name**
- **server/run: maintain state for set/unset params**
- **slice: support filtering**
- **Add support for setting params**
- **move extractParam to its own pkg**
- **server/run: Add CommandWithSetParams**
- **server/run: replace params with their values**
- **param: dedupe multiple instances of a single param**
- **stop using st.Command**
- **set-param: fix title**
- **set-param: use dracula**
- **shell/zsh: add newline after run setup msg**
- **set-param: add command title to share context of the parameter**
- **bash: add support for setting parameters**
- **cmd/set-param: fix spelling**

Add support for runbook parameterization

---

cmd/internal/next.go
cmd/internal/previous.go
server/run/run.go
server/run/run_test.go

- **cmd/internal/next: Add nextCommand func**
- **cmd/internal/next: add --force flag**
- **server/run: Impl previous command.**
- **cmd/internal/previous: allow users to go back when executing runbooks**

next/prev: allow users to skip/retry commands  while executing runbooks

---

client/client.go
cmd/ask.go
cmd/history.go

- **cmd/history: add selectAndExpandHistory func for future reuse**
- **fixup! cmd/history: add selectAndExpandHistory func for future reuse**
- **cmd/ask: allow users to attach historical context to their questions.**
- **cmd/ask: remove short hand flag for --history**

savvy ask: pass in historical commands as context

---

cmd/setup/savvy.zsh

Users associate red with an error and think something went wrong.

display savvy run in green

---

cmd/history.go
cmd/init.go
cmd/setup/fish.go
cmd/setup/savvy.fish
install/install.sh
shell/fish.go
shell/spawn.go

- **shell: Impl Shell for fish**
- **cmd/setup: savvy.fish setup prompt and hooks for recording artifacts**
- **setup: impl fish setup**
- **setup/fish: use well known XDG_DATA_DIRS dir to configure fish shells**
- **cmd/setup/fish: setup script for recording commands.**
- **setup: get status code before copying prompt**
- **setup/fish: use green instead of red for recording**
- **setup/fish: record command as part of pre-exec hook**
- **setup/fish: use post_exec hook to capture exit code.**
- **setup/fish: make step_id global**
- **setup/fish: rename savvy_modify_prompt -> savvy_record_prompt**
- **setup/fish: rm trailing whitespace**
- **setup/fish: impl prompt and cli integration for savvy run**
- **setup/fish: handle case where fish_right_prompt dne**
- **display original prompt on …

Add fish support

---

cmd/ask.go
cmd/history.go
cmd/record.go
export/markdown/markdown.go
export/savvy.go

- **export: Unify code to export a runbook to Savvy into its own pkg**
- **cmd/ask: reuse toListItems when displaying results of savvy ask**
- **export: Select export format**
- **export: impl md export**
- **export: write md to clipboard for easy sharing**

Export commands locally

---

authz/roundtripper.go
client/client.go

Fix a regressions I introduced in an earlier refactor.
The root cause was using ErrInvalidClient in both authz and client pkgs.
This change removes authz's Err to avoid a similar error in the future.

Detect expired tokens and prompt login 
